In [6]:
import pandas as pd
df_311 = pd.read_csv('./tmph4izx_fb.csv')
df_311

,case_enquiry_id,open_dt,target_dt,closed_dt,ontime,case_status,closure_reason,case_title,subject,reason,...,police_district,neighborhood,neighborhood_services_district,ward,precinct,location_street_name,location_zipcode,latitude,longitude,source
0,101004125189,2022-01-13 12:59:00,2022-01-20 12:59:39,NaN,OVERDUE,Open,,Illegal Rooming House,Inspectional Services,Building,...,C11,Dorchester,8,Ward 17,1706,27 Lithgow St,2124.0,42.2896,-71.0701,Constituent Call
1,101004161747,2022-02-02 11:42:49,2022-02-16 11:42:49,2022-02-02 11:45:47,ONTIME,Closed,Case Closed Case Noted,PublicWorks: Complaint,Mayor's 24 Hour Hotline,Employee & General Comments,...,,,,,,NaN,NaN,42.3594,-71.0587,Constituent Call
2,101004149944,2022-01-28 19:36:00,NaN,NaN,ONTIME,Open,,Space Savers,Public Works Department,Sanitation,...,B3,Greater Mattapan,9,Ward 14,1411,492 Harvard St,2124.0,42.2876,-71.0936,Constituent Call
3,101004113302,2022-01-01 00:36:24,2022-01-04 08:30:00,2022-01-03 00:13:17,ONTIME,Closed,Case Closed. Closed date : 2022-01-03 00:13:17...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,C6,South Boston / South Boston Waterfront,5,6,0601,INTERSECTION Seaport Blvd & Sleeper St,NaN,42.3594,-71.0587,Citizens Connect App
4,101004122704,2022-01-11 09:47:00,2022-02-10 09:47:22,NaN,OVERDUE,Open,,DISPATCHED Heat - Excessive Insufficient,Inspectional Services,Housing,...,B2,Roxbury,13,Ward 12,1202,15 Crawford St,2121.0,42.3110,-71.0841,Constituent Call
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276718,101004113407,2022-01-01 09:47:00,NaN,2022-01-01 12:02:05,ONTIME,Closed,Case Closed. Closed date : Sat Jan 01 12:02:05...,Needle Pickup,Mayor's 24 Hour Hotline,Needle Program,...,C6,South Boston / South Boston Waterfront,5,7,0706,INTERSECTION Woodward St & Dorchester St,NaN,42.3594,-71.0587,Constituent Call
276719,101004113448,2022-01-01 10:56:28,2022-01-04 08:30:00,2022-02-09 07:26:36,OVERDUE,Closed,Case Closed. Closed date : Wed Feb 09 07:26:36...,Request for Pothole Repair,Public Works Department,Highway Maintenance,...,D14,Allston / Brighton,15,Ward 21,2114,2 Ayr Rd,2135.0,42.3371,-71.1487,Citizens Connect App
276720,101004113510,2022-01-01 12:39:01,2022-01-04 08:30:00,2022-01-03 06:41:05,ONTIME,Closed,Case Closed. Closed date : Mon Jan 03 06:41:05...,CE Collection,Public Works Department,Street Cleaning,...,D4,South End,4,Ward 3,0307,4 Union Park St,2118.0,42.3419,-71.0701,City Worker App
276721,101004113535,2022-01-01 13:36:00,2022-01-04 08:30:00,2022-01-03 00:07:04,ONTIME,Closed,Case Closed. Closed date : 2022-01-03 00:07:04...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,C11,Dorchester,7,Ward 13,1306,81 Mayfield St,2125.0,42.3172,-71.0608,Constituent Call
276722,101004114271,2022-01-02 21:04:00,NaN,2022-01-03 08:28:07,ONTIME,Closed,Case Closed. Closed date : Mon Jan 03 08:28:07...,Needle Pickup,Mayor's 24 Hour Hotline,Needle Program,...,A1,Boston,3,03,,100 Legends Way,2114.0,42.3663,-71.0622,Constituent Call

In [7]:
df = df_311.groupby('precinct')
df.first()

,case_enquiry_id,open_dt,target_dt,closed_dt,ontime,case_status,closure_reason,case_title,subject,reason,...,city_council_district,police_district,neighborhood,neighborhood_services_district,ward,location_street_name,location_zipcode,latitude,longitude,source
precinct,,,,,,,,,,,,,,,,,,,,,
,101004161747,2022-02-02 11:42:49,2022-02-16 11:42:49,2022-02-02 11:45:47,ONTIME,Closed,Case Closed Case Noted,PublicWorks: Complaint,Mayor's 24 Hour Hotline,Employee & General Comments,...,,,,,,50-150 Causeway St,2114.0,42.3594,-71.0587,Constituent Call
0101,101004115515,2022-01-04 09:01:33,2022-01-05 09:01:33,2022-01-04 12:56:49,ONTIME,Closed,Case Closed. Closed date : 2022-01-04 12:56:49...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,1,A7,East Boston,1,01,213 Webster St,2128.0,42.3649,-71.0332,Citizens Connect App
0102,101004117675,2022-01-06 08:31:45,2022-01-07 08:31:50,2022-01-06 08:37:45,ONTIME,Closed,Case Closed. Closed date : Thu Jan 06 08:37:45...,CE Collection,Public Works Department,Street Cleaning,...,1,A7,East Boston,1,01,174 Gove St,2128.0,42.3594,-71.0587,City Worker App
0103,101004118051,2022-01-06 12:53:00,2022-01-27 12:53:52,2022-01-24 07:23:45,ONTIME,Closed,Case Closed Case Resolved new cart#21026100 d...,Request for Recycling Cart,Public Works Department,Recycling,...,1,A7,East Boston,1,Ward 1,39 Everett St,2128.0,42.3680,-71.0362,Constituent Call
0104,101004117754,2022-01-06 09:15:09,2022-01-07 09:15:09,2022-01-06 09:15:22,ONTIME,Closed,Case Closed. Closed date : 2022-01-06 09:15:22...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,1,A7,East Boston,1,Ward 1,102 London St,2128.0,42.3727,-71.0398,Employee Generated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2209,101004114209,2022-01-02 18:13:37,2022-01-06 08:30:00,2022-01-03 07:41:41,ONTIME,Closed,Case Closed. Closed date : Mon Jan 03 07:41:41...,Poor Conditions of Property,Public Works Department,Code Enforcement,...,9,D14,Allston / Brighton,15,Ward 22,9 Radnor Rd,2135.0,42.3405,-71.1587,Citizens Connect App
2210,101004125591,2022-01-13 19:28:50,2022-02-02 08:30:00,2022-01-18 16:30:47,ONTIME,Closed,Case Closed. Closed date : 2022-01-18 16:30:47...,Schedule Bulk Item Pickup,Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,228 Faneuil St,2135.0,42.3530,-71.1593,Self Service
2211,101004114170,2022-01-02 16:51:48,2023-01-04 09:48:22,2022-01-10 16:30:23,ONTIME,Closed,Case Closed. Closed date : 2022-01-10 16:30:23...,Schedule Bulk Item Pickup,Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,5 Oliva Rd,2135.0,42.3561,-71.1621,Self Service
2212,101004117496,2022-01-05 21:57:00,2022-01-07 08:30:00,2022-01-06 05:49:32,ONTIME,Closed,Case Closed. Closed date : Thu Jan 06 05:49:32...,"Missed ""Other"" Trash: District 04",Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,35 Faneuil St,2135.0,42.3555,-71.1513,Constituent Call
2213,101004125545,2022-01-13 17:59:00,2022-01-12 08:30:00,2022-01-18 16:30:45,ONTIME,Closed,Case Closed. Closed date : 2022-01-18 16:30:45...,Schedule a Bulk Item Pickup,Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,36 Atkins St,2135.0,42.3530,-71.1701,Constituent Call

In [8]:
for name, group in df:
    print('precinct:', name)
    print(group['case_status'].describe())
    print('-----------------')

precinct:
count       3360
unique         2
top       Closed
freq        2601
Name: case_status, dtype: object
-----------------
precinct: 0101
count       1889
unique         2
top       Closed
freq        1771
Name: case_status, dtype: object
-----------------
precinct: 0102
count       1117
unique         2
top       Closed
freq        1047
Name: case_status, dtype: object
-----------------
precinct: 0103
count       1825
unique         2
top       Closed
freq        1695
Name: case_status, dtype: object
-----------------
precinct: 0104
count       1746
unique         2
top       Closed
freq        1676
Name: case_status, dtype: object
-----------------
precinct: 0105
count       1423
unique         2
top       Closed
freq        1350
Name: case_status, dtype: object
-----------------
precinct: 0106
count       1301
unique         2
top       Closed
freq        1245
Name: case_status, dtype: object
-----------------
precinct: 0107
count       1328
unique         2
top       Closed
freq        1241
Name: case_status, dtype: object
-----------------
precinct: 0108
count       1266
unique         2
top       Closed
freq        1195
Name: case_status, dtype: object
-----------------
precinct: 0109
count       1409
unique         2
top       Closed
freq        1341
Name: case_status, dtype: object
-----------------
precinct: 0110
count       1227
unique         2
top       Closed
freq        1142
Name: case_status, dtype: object
-----------------
precinct: 0111
count       1586
unique         2
top       Closed
freq        1446
Name: case_status, dtype: object
-----------------
precinct: 0112
count        944
unique         2
top       Closed
freq         811
Name: case_status, dtype: object
-----------------
precinct: 0113
count       1501
unique         2
top       Closed
freq        1396
Name: case_status, dtype: object
-----------------
precinct: 0114
count        596
unique         2
top       Closed
freq         540
Name: case_status, dtype: object
-----------------
precinct: 0201
count       2195
unique         2
top       Closed
freq        1864
Name: case_status, dtype: object
-----------------
precinct: 0202
count       1211
unique         2
top       Closed
freq         997
Name: case_status, dtype: object
-----------------
precinct: 0203
count        940
unique         2
top       Closed
freq         849
Name: case_status, dtype: object
-----------------
precinct: 0204
count        690
unique         2
top       Closed
freq         602
Name: case_status, dtype: object
-----------------
precinct: 0205
count       1287
unique         2
top       Closed
freq        1168
Name: case_status, dtype: object
-----------------
precinct: 0206
count       1337
unique         2
top       Closed
freq        1199
Name: case_status, dtype: object
-----------------
precinct: 0207
count       1341
unique         2
top       Closed
freq        1172
Name: case_status, dtype: object
-----------------
precinct: 0301
count       2869
unique         2
top       Closed
freq        2585
Name: case_status, dtype: object
-----------------
precinct: 0302
count       2181
unique         2
top       Closed
freq        2038
Name: case_status, dtype: object
-----------------
precinct: 0303
count       2963
unique         2
top       Closed
freq        2774
Name: case_status, dtype: object
-----------------
precinct: 0304
count       2399
unique         2
top       Closed
freq        2211
Name: case_status, dtype: object
-----------------
precinct: 0305
count        736
unique         2
top       Closed
freq         514
Name: case_status, dtype: object
-----------------
precinct: 0306
count       6504
unique         2
top       Closed
freq        5602
Name: case_status, dtype: object
-----------------
precinct: 0307
count       4267
unique         2
top       Closed
freq        3897
Name: case_status, dtype: object
-----------------
precinct: 0308
count       5204
unique         2
top       Closed
freq        4591
Name: case_status, dtype: object
-----------------
precinct: 0401
count       2545
unique         2
top       Closed
freq        2297
Name: case_status, dtype: object
-----------------
precinct: 0402
count       2384
unique         2
top       Closed
freq        1973
Name: case_status, dtype: object
-----------------
precinct: 0403
count       1242
unique         2
top       Closed
freq        1091
Name: case_status, dtype: object
-----------------
precinct: 0404
count       2073
unique         2
top       Closed
freq        1871
Name: case_status, dtype: object
-----------------
precinct: 0405
count       1260
unique         2
top       Closed
freq        1105
Name: case_status, dtype: object
-----------------
precinct: 0406
count        829
unique         2
top       Closed
freq         690
Name: case_status, dtype: object
-----------------
precinct: 0407
count        881
unique         2
top       Closed
freq         703
Name: case_status, dtype: object
-----------------
precinct: 0408
count        652
unique         2
top       Closed
freq         580
Name: case_status, dtype: object
-----------------
precinct: 0409
count        410
unique         2
top       Closed
freq         309
Name: case_status, dtype: object
-----------------
precinct: 0410
count        891
unique         2
top       Closed
freq         674
Name: case_status, dtype: object
-----------------
precinct: 0501
count       5235
unique         2
top       Closed
freq        4744
Name: case_status, dtype: object
-----------------
precinct: 0502
count       1126
unique         2
top       Closed
freq         922
Name: case_status, dtype: object
-----------------
precinct: 0502A
count        404
unique         2
top       Closed
freq         365
Name: case_status, dtype: object
-----------------
precinct: 0503
count       2560
unique         2
top       Closed
freq        2234
Name: case_status, dtype: object
-----------------
precinct: 0504
count       3113
unique         2
top       Closed
freq        2867
Name: case_status, dtype: object
-----------------
precinct: 0505
count        804
unique         2
top       Closed
freq         670
Name: case_status, dtype: object
-----------------
precinct: 0506
count       1205
unique         2
top       Closed
freq        1032
Name: case_status, dtype: object
-----------------
precinct: 0507
count       1926
unique         2
top       Closed
freq        1725
Name: case_status, dtype: object
-----------------
precinct: 0508
count       2398
unique         2
top       Closed
freq        2192
Name: case_status, dtype: object
-----------------
precinct: 0509
count       2983
unique         2
top       Closed
freq        2668
Name: case_status, dtype: object
-----------------
precinct: 0510
count       1047
unique         2
top       Closed
freq         880
Name: case_status, dtype: object
-----------------
precinct: 0511
count       1888
unique         2
top       Closed
freq        1618
Name: case_status, dtype: object
-----------------
precinct: 0601
count       3905
unique         2
top       Closed
freq        3319
Name: case_status, dtype: object
-----------------
precinct: 0602
count       1264
unique         2
top       Closed
freq        1177
Name: case_status, dtype: object
-----------------
precinct: 0603
count       1352
unique         2
top       Closed
freq        1251
Name: case_status, dtype: object
-----------------
precinct: 0604
count       1952
unique         2
top       Closed
freq        1818
Name: case_status, dtype: object
-----------------
precinct: 0605
count       1335
unique         2
top       Closed
freq        1249
Name: case_status, dtype: object
-----------------
precinct: 0606
count       1339
unique         2
top       Closed
freq        1272
Name: case_status, dtype: object
-----------------
precinct: 0607
count       1766
unique         2
top       Closed
freq        1682
Name: case_status, dtype: object
-----------------
precinct: 0608
count       1134
unique         2
top       Closed
freq        1089
Name: case_status, dtype: object
-----------------
precinct: 0609
count       1333
unique         2
top       Closed
freq        1217
Name: case_status, dtype: object
-----------------
precinct: 0701
count       1726
unique         2
top       Closed
freq        1615
Name: case_status, dtype: object
-----------------
precinct: 0702
count       1471
unique         2
top       Closed
freq        1378
Name: case_status, dtype: object
-----------------
precinct: 0703
count       1659
unique         2
top       Closed
freq        1550
Name: case_status, dtype: object
-----------------
precinct: 0704
count       1296
unique         2
top       Closed
freq        1229
Name: case_status, dtype: object
-----------------
precinct: 0705
count       1684
unique         2
top       Closed
freq        1603
Name: case_status, dtype: object
-----------------
precinct: 0706
count       1505
unique         2
top       Closed
freq        1406
Name: case_status, dtype: object
-----------------
precinct: 0707
count        749
unique         2
top       Closed
freq         607
Name: case_status, dtype: object
-----------------
precinct: 0708
count       1525
unique         2
top       Closed
freq        1402
Name: case_status, dtype: object
-----------------
precinct: 0709
count       1217
unique         2
top       Closed
freq        1078
Name: case_status, dtype: object
-----------------
precinct: 0710
count       1101
unique         2
top       Closed
freq        1021
Name: case_status, dtype: object
-----------------
precinct: 0801
count        898
unique         2
top       Closed
freq         704
Name: case_status, dtype: object
-----------------
precinct: 0802
count       3736
unique         2
top       Closed
freq        3411
Name: case_status, dtype: object
-----------------
precinct: 0803
count       1190
unique         2
top       Closed
freq        1069
Name: case_status, dtype: object
-----------------
precinct: 0804
count        416
unique         2
top       Closed
freq         359
Name: case_status, dtype: object
-----------------
precinct: 0805
count        716
unique         2
top       Closed
freq         639
Name: case_status, dtype: object
-----------------
precinct: 0806
count       1463
unique         2
top       Closed
freq        1348
Name: case_status, dtype: object
-----------------
precinct: 0807
count        742
unique         2
top       Closed
freq         691
Name: case_status, dtype: object
-----------------
precinct: 0901
count       1604
unique         2
top       Closed
freq        1421
Name: case_status, dtype: object
-----------------
precinct: 0902
count       2305
unique         2
top       Closed
freq        2128
Name: case_status, dtype: object
-----------------
precinct: 0903
count       2101
unique         2
top       Closed
freq        1987
Name: case_status, dtype: object
-----------------
precinct: 0904
count       1398
unique         2
top       Closed
freq        1246
Name: case_status, dtype: object
-----------------
precinct: 0905
count       1564
unique         2
top       Closed
freq        1397
Name: case_status, dtype: object
-----------------
precinct: 1001
count        175
unique         2
top       Closed
freq         150
Name: case_status, dtype: object
-----------------
precinct: 1002
count        786
unique         2
top       Closed
freq         686
Name: case_status, dtype: object
-----------------
precinct: 1003
count        699
unique         2
top       Closed
freq         615
Name: case_status, dtype: object
-----------------
precinct: 1004
count        953
unique         2
top       Closed
freq         862
Name: case_status, dtype: object
-----------------
precinct: 1005
count        853
unique         2
top       Closed
freq         782
Name: case_status, dtype: object
-----------------
precinct: 1006
count        643
unique         2
top       Closed
freq         585
Name: case_status, dtype: object
-----------------
precinct: 1007
count        619
unique         2
top       Closed
freq         527
Name: case_status, dtype: object
-----------------
precinct: 1008
count       1709
unique         2
top       Closed
freq        1538
Name: case_status, dtype: object
-----------------
precinct: 1009
count        972
unique         2
top       Closed
freq         882
Name: case_status, dtype: object
-----------------
precinct: 1101
count        981
unique         2
top       Closed
freq         884
Name: case_status, dtype: object
-----------------
precinct: 1102
count        863
unique         2
top       Closed
freq         787
Name: case_status, dtype: object
-----------------
precinct: 1103
count        500
unique         2
top       Closed
freq         457
Name: case_status, dtype: object
-----------------
precinct: 1104
count       1172
unique         2
top       Closed
freq        1055
Name: case_status, dtype: object
-----------------
precinct: 1105
count       1005
unique         2
top       Closed
freq         890
Name: case_status, dtype: object
-----------------
precinct: 1106
count        848
unique         2
top       Closed
freq         718
Name: case_status, dtype: object
-----------------
precinct: 1107
count        917
unique         2
top       Closed
freq         796
Name: case_status, dtype: object
-----------------
precinct: 1108
count       1165
unique         2
top       Closed
freq         971
Name: case_status, dtype: object
-----------------
precinct: 1109
count        518
unique         2
top       Closed
freq         452
Name: case_status, dtype: object
-----------------
precinct: 1110
count        607
unique         2
top       Closed
freq         522
Name: case_status, dtype: object
-----------------
precinct: 1201
count       1106
unique         2
top       Closed
freq         994
Name: case_status, dtype: object
-----------------
precinct: 1202
count        914
unique         2
top       Closed
freq         798
Name: case_status, dtype: object
-----------------
precinct: 1203
count        506
unique         2
top       Closed
freq         450
Name: case_status, dtype: object
-----------------
precinct: 1204
count        899
unique         2
top       Closed
freq         843
Name: case_status, dtype: object
-----------------
precinct: 1205
count        350
unique         2
top       Closed
freq         315
Name: case_status, dtype: object
-----------------
precinct: 1206
count        586
unique         2
top       Closed
freq         497
Name: case_status, dtype: object
-----------------
precinct: 1207
count       1623
unique         2
top       Closed
freq        1473
Name: case_status, dtype: object
-----------------
precinct: 1208
count        548
unique         2
top       Closed
freq         498
Name: case_status, dtype: object
-----------------
precinct: 1209
count        536
unique         2
top       Closed
freq         495
Name: case_status, dtype: object
-----------------
precinct: 1301
count       1024
unique         2
top       Closed
freq         957
Name: case_status, dtype: object
-----------------
precinct: 1302
count        322
unique         2
top       Closed
freq         285
Name: case_status, dtype: object
-----------------
precinct: 1303
count        138
unique         2
top       Closed
freq          89
Name: case_status, dtype: object
-----------------
precinct: 1304
count        573
unique         2
top       Closed
freq         516
Name: case_status, dtype: object
-----------------
precinct: 1305
count        689
unique         2
top       Closed
freq         641
Name: case_status, dtype: object
-----------------
precinct: 1306
count       1442
unique         2
top       Closed
freq        1343
Name: case_status, dtype: object
-----------------
precinct: 1307
count       1218
unique         2
top       Closed
freq        1114
Name: case_status, dtype: object
-----------------
precinct: 1308
count        814
unique         2
top       Closed
freq         768
Name: case_status, dtype: object
-----------------
precinct: 1309
count       1118
unique         2
top       Closed
freq        1063
Name: case_status, dtype: object
-----------------
precinct: 1310
count       1533
unique         2
top       Closed
freq        1380
Name: case_status, dtype: object
-----------------
precinct: 1401
count       1411
unique         2
top       Closed
freq        1304
Name: case_status, dtype: object
-----------------
precinct: 1402
count       1158
unique         2
top       Closed
freq        1033
Name: case_status, dtype: object
-----------------
precinct: 1403
count        812
unique         2
top       Closed
freq         729
Name: case_status, dtype: object
-----------------
precinct: 1404
count        913
unique         2
top       Closed
freq         852
Name: case_status, dtype: object
-----------------
precinct: 1405
count        661
unique         2
top       Closed
freq         602
Name: case_status, dtype: object
-----------------
precinct: 1406
count        501
unique         2
top       Closed
freq         431
Name: case_status, dtype: object
-----------------
precinct: 1407
count        635
unique         2
top       Closed
freq         582
Name: case_status, dtype: object
-----------------
precinct: 1408
count        689
unique         2
top       Closed
freq         575
Name: case_status, dtype: object
-----------------
precinct: 1409
count        710
unique         2
top       Closed
freq         633
Name: case_status, dtype: object
-----------------
precinct: 1410
count        531
unique         2
top       Closed
freq         463
Name: case_status, dtype: object
-----------------
precinct: 1411
count        599
unique         2
top       Closed
freq         530
Name: case_status, dtype: object
-----------------
precinct: 1412
count        412
unique         2
top       Closed
freq         356
Name: case_status, dtype: object
-----------------
precinct: 1413
count        391
unique         2
top       Closed
freq         363
Name: case_status, dtype: object
-----------------
precinct: 1414
count        617
unique         2
top       Closed
freq         534
Name: case_status, dtype: object
-----------------
precinct: 1501
count        837
unique         2
top       Closed
freq         766
Name: case_status, dtype: object
-----------------
precinct: 1502
count        536
unique         2
top       Closed
freq         492
Name: case_status, dtype: object
-----------------
precinct: 1503
count        358
unique         2
top       Closed
freq         321
Name: case_status, dtype: object
-----------------
precinct: 1504
count       1222
unique         2
top       Closed
freq        1112
Name: case_status, dtype: object
-----------------
precinct: 1505
count        550
unique         2
top       Closed
freq         503
Name: case_status, dtype: object
-----------------
precinct: 1506
count        573
unique         2
top       Closed
freq         519
Name: case_status, dtype: object
-----------------
precinct: 1507
count        630
unique         2
top       Closed
freq         587
Name: case_status, dtype: object
-----------------
precinct: 1508
count        584
unique         2
top       Closed
freq         512
Name: case_status, dtype: object
-----------------
precinct: 1509
count        801
unique         2
top       Closed
freq         745
Name: case_status, dtype: object
-----------------
precinct: 1601
count        882
unique         2
top       Closed
freq         793
Name: case_status, dtype: object
-----------------
precinct: 1602
count        924
unique         2
top       Closed
freq         787
Name: case_status, dtype: object
-----------------
precinct: 1603
count        978
unique         2
top       Closed
freq         916
Name: case_status, dtype: object
-----------------
precinct: 1604
count        792
unique         2
top       Closed
freq         719
Name: case_status, dtype: object
-----------------
precinct: 1605
count        874
unique         2
top       Closed
freq         793
Name: case_status, dtype: object
-----------------
precinct: 1606
count        939

In [9]:
import pandas as pd
xl = pd.ExcelFile('./census_data_for_2022_redistricting.xlsx')
xl.sheet_names
census_df = xl.parse('2020')
census_df

,Unnamed: 0,Total Population by Race and Ethnicity,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26,Housing Units,Unnamed: 28,Unnamed: 29
0,Ward and Precinct (Updated 2022),Total Population,White alone,Black or African American,Hispanic or Latino (of any Race),Asian,American Indian and Alaska Native,Native Hawaiian and Other Pacific Islander,Some Other Race,Two or More Non-White Races,...,Correctional Facilities for Adults,Juvenile Facilities,Nursing Facilities,Other Institutional Facilities,College / University Student Housing,Military Quarters,Other Noninstitutional Facilities,Total Housing Units,Occupied Housing Units,Vacant Housing Units
1,0101,2340,1420,67,652,87,21,2,67,24,...,0,0,0,0,0,0,10,1121,1026,95
2,0102,2603,994,81,1303,104,2,1,91,27,...,0,0,0,0,0,0,0,1083,1012,71
3,0103,5111,2287,328,1804,479,16,2,148,47,...,0,0,0,0,0,0,0,2815,2576,239
4,0104,3019,1113,133,1494,173,11,0,70,25,...,0,12,0,0,0,0,24,1435,1306,129
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
274,2212,2206,926,205,576,345,3,4,134,13,...,0,0,0,0,0,0,9,822,791,31
275,2213,1513,1138,54,140,150,2,0,21,8,...,0,0,99,0,0,0,0,597,586,11
276,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
277,"Source: U.S. Census Bureau, 2020 Decennial Cen...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
278,See notes tab for detailed description of race...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
census_df.columns = census_df.iloc[0]
census_df = census_df[1:]
census_df.to_csv('./census_boston_2020.csv')
census_df = census_df[:275]
census_df

,Ward and Precinct (Updated 2022),Total Population,White alone,Black or African American,Hispanic or Latino (of any Race),Asian,American Indian and Alaska Native,Native Hawaiian and Other Pacific Islander,Some Other Race,Two or More Non-White Races,...,Correctional Facilities for Adults,Juvenile Facilities,Nursing Facilities,Other Institutional Facilities,College / University Student Housing,Military Quarters,Other Noninstitutional Facilities,Total Housing Units,Occupied Housing Units,Vacant Housing Units
1,0101,2340,1420,67,652,87,21,2,67,24,...,0,0,0,0,0,0,10,1121,1026,95
2,0102,2603,994,81,1303,104,2,1,91,27,...,0,0,0,0,0,0,0,1083,1012,71
3,0103,5111,2287,328,1804,479,16,2,148,47,...,0,0,0,0,0,0,0,2815,2576,239
4,0104,3019,1113,133,1494,173,11,0,70,25,...,0,12,0,0,0,0,24,1435,1306,129
5,0105,3539,1124,93,1958,158,19,1,156,30,...,0,0,0,0,0,0,15,1418,1315,103
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
271,2209,2347,1636,68,120,452,3,1,60,7,...,0,0,0,0,0,0,31,1071,1015,56
272,2210,2279,1633,103,201,250,8,0,69,15,...,0,0,0,0,0,0,12,1021,985,36
273,2211,1663,1096,63,144,271,7,1,65,16,...,0,0,0,0,0,0,1,623,598,25
274,2212,2206,926,205,576,345,3,4,134,13,...,0,0,0,0,0,0,9,822,791,31
275,2213,1513,1138,54,140,150,2,0,21,8,...,0,0,99,0,0,0,0,597,586,11

In [11]:
census_df.columns

Index(['Ward and Precinct (Updated 2022)', 'Total Population', 'White alone',
       'Black or African American', 'Hispanic or Latino (of any Race)',
       'Asian', 'American Indian and Alaska Native',
       'Native Hawaiian and Other Pacific Islander', 'Some Other Race',
       'Two or More Non-White Races', 'Total Population,\nAge 18 and over',
       'White alone,\nAge 18 and over',
       'Black or African American,\nAge 18 and over',
       'Hispanic or Latino (of any Race),\nAge 18 and over',
       'Asian,\nAge 18 and over',
       'American Indian and Alaska Native,\nAge 18 and over',
       'Native Hawaiian and Other Pacific Islander,\nAge 18 and over',
       'Some Other Race,\nAge 18 and over',
       'Two or More Non-White Races,\nAge 18 and over',
       'Total Group Quarters Population', 'Correctional Facilities for Adults',
       'Juvenile Facilities', 'Nursing Facilities',
       'Other Institutional Facilities',
       'College / University Student Housing', 'Military Quarters',
       'Other Noninstitutional Facilities', 'Total Housing Units',
       'Occupied Housing Units', 'Vacant Housing Units'],
      dtype='object', name=0)

In [12]:
census_df['White alone ratio,\nAge 18 and over'] = (census_df['White alone,\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [13]:
census_df['Black or African American ratio,\nAge 18 and over'] = (census_df['Black or African American,\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [14]:
census_df['Hispanic or Latino (of any Race) ratio,\nAge 18 and over'] = (census_df['Hispanic or Latino (of any Race),\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [15]:
census_df['Asian ratio,\nAge 18 and over'] = (census_df['Asian,\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [16]:
census_df['American Indian and Alaska Native ratio,\nAge 18 and over'] = (census_df['American Indian and Alaska Native,\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [17]:
census_df['Native Hawaiian and Other Pacific Islander ratio,\nAge 18 and over'] = (census_df['Native Hawaiian and Other Pacific Islander,\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [18]:
census_df['Some Other Race rato,\nAge 18 and over'] = (census_df['Some Other Race,\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [19]:
census_df['Two or More Non-White Races ratio,\nAge 18 and over'] = (census_df['Two or More Non-White Races,\nAge 18 and over']) / (census_df['Total Population,\nAge 18 and over']+1)

In [20]:
census_df.to_csv('./census_boston_2020.csv')

In [21]:
census_df.index = census_df['Ward and Precinct (Updated 2022)']
df_311 = pd.read_csv('./tmph4izx_fb.csv')
gp_precinct_311 = df_311.groupby('precinct')
gp_precinct_311.first()

,case_enquiry_id,open_dt,target_dt,closed_dt,ontime,case_status,closure_reason,case_title,subject,reason,...,city_council_district,police_district,neighborhood,neighborhood_services_district,ward,location_street_name,location_zipcode,latitude,longitude,source
precinct,,,,,,,,,,,,,,,,,,,,,
,101004161747,2022-02-02 11:42:49,2022-02-16 11:42:49,2022-02-02 11:45:47,ONTIME,Closed,Case Closed Case Noted,PublicWorks: Complaint,Mayor's 24 Hour Hotline,Employee & General Comments,...,,,,,,50-150 Causeway St,2114.0,42.3594,-71.0587,Constituent Call
0101,101004115515,2022-01-04 09:01:33,2022-01-05 09:01:33,2022-01-04 12:56:49,ONTIME,Closed,Case Closed. Closed date : 2022-01-04 12:56:49...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,1,A7,East Boston,1,01,213 Webster St,2128.0,42.3649,-71.0332,Citizens Connect App
0102,101004117675,2022-01-06 08:31:45,2022-01-07 08:31:50,2022-01-06 08:37:45,ONTIME,Closed,Case Closed. Closed date : Thu Jan 06 08:37:45...,CE Collection,Public Works Department,Street Cleaning,...,1,A7,East Boston,1,01,174 Gove St,2128.0,42.3594,-71.0587,City Worker App
0103,101004118051,2022-01-06 12:53:00,2022-01-27 12:53:52,2022-01-24 07:23:45,ONTIME,Closed,Case Closed Case Resolved new cart#21026100 d...,Request for Recycling Cart,Public Works Department,Recycling,...,1,A7,East Boston,1,Ward 1,39 Everett St,2128.0,42.3680,-71.0362,Constituent Call
0104,101004117754,2022-01-06 09:15:09,2022-01-07 09:15:09,2022-01-06 09:15:22,ONTIME,Closed,Case Closed. Closed date : 2022-01-06 09:15:22...,Parking Enforcement,Transportation - Traffic Division,Enforcement & Abandoned Vehicles,...,1,A7,East Boston,1,Ward 1,102 London St,2128.0,42.3727,-71.0398,Employee Generated
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2209,101004114209,2022-01-02 18:13:37,2022-01-06 08:30:00,2022-01-03 07:41:41,ONTIME,Closed,Case Closed. Closed date : Mon Jan 03 07:41:41...,Poor Conditions of Property,Public Works Department,Code Enforcement,...,9,D14,Allston / Brighton,15,Ward 22,9 Radnor Rd,2135.0,42.3405,-71.1587,Citizens Connect App
2210,101004125591,2022-01-13 19:28:50,2022-02-02 08:30:00,2022-01-18 16:30:47,ONTIME,Closed,Case Closed. Closed date : 2022-01-18 16:30:47...,Schedule Bulk Item Pickup,Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,228 Faneuil St,2135.0,42.3530,-71.1593,Self Service
2211,101004114170,2022-01-02 16:51:48,2023-01-04 09:48:22,2022-01-10 16:30:23,ONTIME,Closed,Case Closed. Closed date : 2022-01-10 16:30:23...,Schedule Bulk Item Pickup,Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,5 Oliva Rd,2135.0,42.3561,-71.1621,Self Service
2212,101004117496,2022-01-05 21:57:00,2022-01-07 08:30:00,2022-01-06 05:49:32,ONTIME,Closed,Case Closed. Closed date : Thu Jan 06 05:49:32...,"Missed ""Other"" Trash: District 04",Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,35 Faneuil St,2135.0,42.3555,-71.1513,Constituent Call
2213,101004125545,2022-01-13 17:59:00,2022-01-12 08:30:00,2022-01-18 16:30:45,ONTIME,Closed,Case Closed. Closed date : 2022-01-18 16:30:45...,Schedule a Bulk Item Pickup,Public Works Department,Sanitation,...,9,D14,Allston / Brighton,15,Ward 22,36 Atkins St,2135.0,42.3530,-71.1701,Constituent Call

In [22]:
ontime_rate = gp_precinct_311['ontime'].aggregate(lambda x: sum([y=='ONTIME' for y in x]) / len(x) )
census_df['White alone ratio,\nAge 18 and over'].corr(ontime_rate, method='spearman')

0.022044702799942712

In [23]:
census_df['Black or African American ratio,\nAge 18 and over'].corr(ontime_rate, method='spearman')

-0.14448961166439084

In [24]:
census_df['Hispanic or Latino (of any Race) ratio,\nAge 18 and over'].corr(ontime_rate, method='spearman')

0.015978250742231945

In [25]:
census_df['Asian ratio,\nAge 18 and over'].corr(ontime_rate, method='spearman')

-0.12544141623632105

In [26]:
census_df['American Indian and Alaska Native ratio,\nAge 18 and over'].corr(ontime_rate, method='spearman')

0.016158208342122712

In [27]:
census_df['Native Hawaiian and Other Pacific Islander ratio,\nAge 18 and over'].corr(ontime_rate, method='spearman')

0.033180079233786026

In [28]:
census_df['Some Other Race rato,\nAge 18 and over'].corr(ontime_rate, method='spearman')

0.04345239847168873

In [29]:
census_df['Two or More Non-White Races ratio,\nAge 18 and over'].corr(ontime_rate, method='spearman')

-0.0017516985983599507

case_status

In [30]:
case_status_rate = gp_precinct_311['case_status'].aggregate(lambda x: sum([y=='Open' for y in x]) / len(x) )
census_df['White alone ratio,\nAge 18 and over'].corr(case_status_rate, method='spearman')

0.10469848531687201

In [31]:
census_df['Black or African American ratio,\nAge 18 and over'].corr(case_status_rate, method='spearman')

0.06964351696236389

In [32]:
census_df['Hispanic or Latino (of any Race) ratio,\nAge 18 and over'].corr(case_status_rate, method='spearman')

-0.09507953320523034

In [33]:
census_df['Asian ratio,\nAge 18 and over'].corr(case_status_rate, method='spearman')

0.06701204480479918

In [34]:
census_df['American Indian and Alaska Native ratio,\nAge 18 and over'].corr(case_status_rate, method='spearman')

-0.0380504412249721

In [35]:
census_df['Native Hawaiian and Other Pacific Islander ratio,\nAge 18 and over'].corr(case_status_rate, method='spearman')

-0.0812096752885193

In [36]:
census_df['Some Other Race rato,\nAge 18 and over'].corr(case_status_rate, method='spearman')

-0.1691480526784459

In [37]:
census_df['Two or More Non-White Races ratio,\nAge 18 and over'].corr(case_status_rate, method='spearman')

-0.11791685804002437